"""Compaction-on-upgrade: when a session switches UP a tier mid-conversation,
ask MiniMax to summarize the prior turns and rewrite the messages array so
the upgraded tier (typically Anthropic) starts from a coherent summary
instead of a partial history written by a weaker model.

Why this exists
---------------
Routing decisions are PER TURN. If a session lives at minimax_ok for 4 turns,
then on turn 5 the classifier upgrades to frontier, the frontier model
inherits 4 assistant turns generated by MiniMax. Those turns can be:
- factually wrong (MiniMax confidently hallucinating an API)
- low-resolution (terse where a frontier reply would have been thorough)
- shaped by MiniMax's "voice" rather than the frontier model's

Sending the raw history pollutes the frontier turn. Compaction replaces the
prior history with a fresh single-paragraph summary generated by MiniMax
itself, plus a tiny synthetic assistant ack, plus the user's latest message.
The frontier model sees: "summary of where we are" → "ack" → "user's question".

Why MiniMax for the summary
---------------------------
The summary is short and structured; it doesn't need frontier quality. Using
MiniMax keeps compaction cheap (~$0.001 / call vs ~$0.05 for Sonnet) and
amortizes the compute we were already paying for the lower-tier turns.

Failure mode
------------
ALWAYS fail-open. If the compaction call errors / times out, we return the
original body unchanged and let the frontier model receive the raw history.
A messy turn is strictly better than a dropped turn.

Latency cost
------------
~1-3s on the compacted turn. Subsequent turns at the upgraded tier reuse
the rewritten history (cached at the backend) and pay no compaction cost.
Downgrades skip compaction entirely — frontier-quality history into MiniMax
is a feature, not a bug.

See `shared-docs/inferroute/stability-and-routing.md` for the broader design.
"""
from __future__ import annotations

import copy
import logging
from typing import Optional

import httpx

from .config import Config
from .router import RouterDecision

logger = logging.getLogger("inferroute_local.compactor")

# Summarization prompt. Short, structured, opinionated about what to keep.
# Bullets > prose because the consumer (frontier model) reads them quickly,
# and because bullets force MiniMax to be concrete instead of waxing.
_SUMMARY_PROMPT = (
    "Summarize the conversation above as a handoff briefing for another assistant "
    "that will take over starting now. Use 5–10 bullets, in this order: "
    "(1) the user's goal, "
    "(2) any decisions already made, "
    "(3) files / commands / state currently in play, "
    "(4) what is still pending or unresolved. "
    "Be concrete, name files and identifiers exactly. Do NOT add advice — the next "
    "assistant decides what to do. Plain text bullets, no preamble, no closing remarks."
)


def should_compact(decision: RouterDecision, body: dict, config: Config) -> bool:
    """True iff this turn should trigger a compaction call.

    Compaction fires only when ALL of these hold:
      - feature enabled in config
      - router signalled an upgrade (lower tier → higher tier)
      - prior history is long enough to be worth summarizing
      - the latest message is from the user (we'd otherwise be summarizing into
        the middle of an assistant turn, which makes no sense)
    """
    if not config.compactor_enabled:
        return False
    if not decision.is_upgrade:
        return False
    messages = body.get("messages") or []
    if len(messages) < config.compactor_min_messages:
        return False
    if messages[-1].get("role") != "user":
        return False
    return True


async def maybe_compact(
    body: dict,
    decision: RouterDecision,
    client: httpx.AsyncClient,
    config: Config,
) -> tuple[dict, Optional[str]]:
    """Possibly rewrite the messages array. Returns (new_body, status_label).

    status_label is one of:
      None             — compaction not applicable
      "compacted"      — succeeded
      "compact_failed" — call errored, original body returned
      "compact_empty"  — summarizer returned no text, original body returned
    """
    if not should_compact(decision, body, config):
        return body, None

    messages = body["messages"]
    prior = messages[:-1]
    latest_user = messages[-1]

    try:
        summary = await _summarize(prior, client, config)
    except Exception as e:
        logger.warning(
            f"compaction call failed ({type(e).__name__}: {e}); "
            "forwarding original history to upgraded tier"
        )
        return body, "compact_failed"

    if not summary:
        logger.info("compactor produced empty summary; forwarding original history")
        return body, "compact_empty"

    rewritten = copy.deepcopy(body)
    rewritten["messages"] = [
        {
            "role": "user",
            "content": (
                f"[Previous-conversation summary — generated for tier-upgrade handoff "
                f"from {decision.previous_tier} → {decision.tier}]\n\n{summary}"
            ),
        },
        {"role": "assistant", "content": "Got it — continuing from there."},
        latest_user,
    ]
    return rewritten, "compacted"


async def _summarize(
    prior_messages: list, client: httpx.AsyncClient, config: Config
) -> str:
    """Ask MiniMax (via inferroute-server) for a summary. Returns plain text.

    We send the full prior history followed by our summarization instruction.
    The inferroute-server already routes `MiniMax-M2.5-TEE` to the right
    backend, so we just have to set model+auth.
    """
    request = {
        "model": config.minimax_model,
        "max_tokens": config.compactor_max_summary_tokens,
        "messages": [
            *prior_messages,
            {"role": "user", "content": _SUMMARY_PROMPT},
        ],
    }
    headers = {
        "content-type": "application/json",
        "authorization": f"Bearer {config.inferroute_api_key}",
        "anthropic-version": "2023-06-01",
        # Tag so server logs can distinguish compaction traffic from primary turns.
        "x-inferroute-purpose": "compaction",
    }
    resp = await client.post(
        f"{config.inferroute_server_url}/v1/messages",
        json=request,
        headers=headers,
        timeout=httpx.Timeout(config.compactor_timeout_s),
    )
    resp.raise_for_status()
    data = resp.json()
    # Anthropic-shaped response: top-level `content` is a list of content blocks.
    blocks = data.get("content") or []
    parts = [
        b.get("text", "")
        for b in blocks
        if isinstance(b, dict) and b.get("type") == "text"
    ]
    return "\n".join(p for p in parts if p).strip()
